"use strict";
console.log("Hey there, I have started learning TYPESCRIPT");
var myName = "Ahtisham ul Haq";
console.log("My name is:", myName);
var num1 = 50;
var num2 = 35;
var num3 = 10;
var num4 = 28;
var num5 = 7;
var num6 = 75;
var num7 = 44;
var num8 = 63;
var num9 = 2;
var num10 = 17;
var sum = num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num9 + num10;
console.log("The sum of numbers is:", sum);
var subtraction = num1 - num2 - num3 - num4 - num5 - num6 - num7 - num8 - num9 - num10;
console.log("The subtraction of numbers is:", subtraction);
var multiplication = num1 * num2 * num3 * num4 * num5 * num6 * num7 * num8 * num9 * num10;
console.log("The multiplication of numbers is:", multiplication);
var division = num7 / num9;
console.log("The division of numbers is:", division);
var allOperations = num2 - num10 * num7 + num4 / num9;
console.log("The result of performing all the operations is:", allOperations);
